### ISSUE TITLE
GP_U2_CALIDAD DE SOFTWARE:SINTESIS_ANGELESGONZALEZMARTINEZ

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-ang3-l32#1]
[GP_U2_SINTESIS_CALIDADDESOFTWARE_ANGELESGONZALEZMARTINEZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-ang3-l32/files/12717600/GP_U2_SINTESIS_CALIDADDESOFTWARE_ANGELESGONZALEZMARTINEZ.pdf)

**Comment by abicoronel** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
